apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  ports:
  - name: spark-submit
    port: 7077
  selector:
    name: spark-master
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-admin
spec:
  type: NodePort 
  ports:
  - name: admin-http
    port: 6060
    nodePort: 30004
  selector:
    name: spark-master
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    name: spark-master
  template:
    metadata:
      labels:
        name: spark-master
    spec:
      containers:
      - name: spark-master
        image: meetup-session3-spark-master
        imagePullPolicy: Never
        env:
        - name: SPARK_MASTER_PORT
          value: "7077"
        ports:
        - containerPort: 6060
        - containerPort: 7077
