apiVersion: v1
kind: Service
metadata:
  name: spark-slave-admin
spec:
  type: NodePort 
  ports:
  - name: admin-http
    port: 6061
  selector:
    name: spark-slave
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: spark-slave
spec:
  replicas: 1
  selector:
    name: spark-slave
  template:
    metadata:
      labels:
        name: spark-slave
    spec:
      containers:
      - name: spark-slave
        image: meetup-session3-spark-slave
        imagePullPolicy: Never
        resources:
          requests:
            memory: "1024M"
            cpu: "150m"
          limits:
            cpu: "250m"
        volumeMounts:
        - mountPath: /data-sets
          name: data
        env:
        - name: SPARK_WORKER_CORES
          value: "1"
        - name: SPARK_WORKER_MEMORY
          value: 1G
        - name: SPARK_MASTER
          value: spark://spark-master:7077
        ports:
        - containerPort: 6061
      volumes:
        - name: data
          hostPath:
            path: /var/lib/zeppelin/data-sets
